name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libcurl4-openssl-dev libdeflate-dev
    - name: make
      run: make
    - name: Run tests
      run: |
        ./bin/longcallD --version
    # - name: make check
    #  run: make check
