name: Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev libdeflate-dev
    - name: make
      run: make
    - name: Run tests
      run: |
        ./bin/longcallD call --version