name: MacOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    strategy:
      matrix:
        os: [macos-latest, macos-13] # test on arm64 and x64
    runs-on: ${{ matrix.os }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: |
        brew update
        brew install autoconf automake make gcc perl zlib bzip2 xz curl openssl libdeflate
    - name: make
      run: make
    - name: Run tests
      run: |
        ./bin/longcallD call --version
